### ISSUE TITLE
Applied conventions on 9 repositories

### ISSUE THREAD

**Issue by madebr** [madebr/dummy_community#9]
Hello,
    
`bincrafters-conventions` and `conan-readme-generator` were executed on the following repositories:

- [ ] conan-freetype: stable/2.9.1 madebr/conan-freetype#2
- [ ] conan-lcms: stable/2.9 madebr/conan-lcms#2
- [ ] conan-libiconv: stable/1.15 madebr/conan-libiconv#2
- [ ] conan-libjpeg: stable/9c madebr/conan-libjpeg#2
- [ ] conan-libpng: stable/1.6.37 madebr/conan-libpng#2
- [ ] conan-libtiff: stable/4.0.9 madebr/conan-libtiff#2
- [ ] conan-libwebp: stable/1.0.0 madebr/conan-libwebp#2
- [ ] conan-libxml2: stable/2.9.9 madebr/conan-libxml2#2
- [ ] conan-lzma: stable/5.2.4 madebr/conan-lzma#2

###### auto-generated using conan-repo-actions
